---
id: use-wireguard
base_name: use-wireguard
tags:
- wireguard
- linux
presentation_date: 2020/04/18
version: 2020.04.18
licenses: []
slideshare_id: wireguard
speaker_deck_id: wireguard-shi-jian-ru-men
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
